spring:
  application:
    name: ms_pistas

  datasource:
    url: jdbc:postgresql://postgres_pistas:5432/pistas
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

server:
  port: 8080